productslist/config/routes.rb
Rails.application.routes.draw do
  root :to => 'host/admin/products#index'

  namespace :host do
    namespace :admin do
      resources :products, :only => [:index, :edit, :update] do
        member do
          post :add_tag
          delete :remove_tag
          post :add_category
          delete :remove_category
        end
      end
    end

  end

  namespace :api, :format => true, :constraints => { :format => 'json' } do
    namespace :v1 do
      resource :products, :only => [:create]
    end
  end

end

productslist/app/models/category.rb
=begin
schema
+----------------+------------------+------+-----+---------+----------------+
| Field          | Type             | Null | Key | Default | Extra          |
+----------------+------------------+------+-----+---------+----------------+
| id             | int(11)          | NO   | PRI | NULL    | auto_increment |
| name           | varchar(255)     | YES  |     | NULL    |                |
+----------------+------------------+------+-----+---------+----------------+
=end

class Category < ActiveRecord::Base
  has_and_belongs_to_many :products,
                          :join_table => :products_categories
end

productslist/app/models/product.rb
=begin
schema
+----------------+------------------+------+-----+---------+----------------+
| Field          | Type             | Null | Key | Default | Extra          |
+----------------+------------------+------+-----+---------+----------------+
| id             | int(11)          | NO   | PRI | NULL    | auto_increment |
| sku_id         | varchar(255)     | NO   |     | NULL    |                |
| name           | varchar(255)     | YES  |     | NULL    |                |
| expire_date    | date             | YES  |     | NULL    |                |
| images         | text             | YES  |     | NULL    |                |
| price          | int(11) unsigned | YES  |     | 0       |                |
| description    | text             | YES  |     | NULL    |                |
| admin_approved | tinyint(1)       | YES  |     | 0       |                |
| created_at     | datetime         | YES  |     | NULL    |                |
| updated_at     | datetime         | YES  |     | NULL    |                |
+----------------+------------------+------+-----+---------+----------------+
=end

class Product < ActiveRecord::Base
  validates :sku_id, :uniqueness => true, :presence => true

  serialize :images, Array

  has_and_belongs_to_many :categories,
                          :join_table => :products_categories
  has_and_belongs_to_many :tags,
                          :join_table => :products_tags

  scope :with_tag, -> (tag_name) {
    where('tags.name = ?', tag_name).joins(:tags)}

  scope :with_category, -> (category_name) {
    where('categories.name = ?', category_name).joins(:categories)}

  def images
    Array(super)
  end

  def first_image_url
    if images.present?
      images.first.with_indifferent_access[:image_path]
    end
  end
end

productslist/app/models/tag.rb
=begin
schema
+----------------+------------------+------+-----+---------+----------------+
| Field          | Type             | Null | Key | Default | Extra          |
+----------------+------------------+------+-----+---------+----------------+
| id             | int(11)          | NO   | PRI | NULL    | auto_increment |
| name           | varchar(255)     | YES  |     | NULL    |                |
+----------------+------------------+------+-----+---------+----------------+
=end

class Tag < ActiveRecord::Base
  has_and_belongs_to_many :products,
                          :join_table => :products_tags
end

productslist/app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ApiController

  def create
    respond_to do |format|
      product = ProductsService.new.create_product(product_params)

      if product.valid?
        format.json {
          render(:json => {
            :product => product
          })
        }
      else
        format.json {
          render(
            :json => product.errors.full_messages.join(', '),
            :status => :unprocessable_entity,
          )
        }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(
      :sku_id,
      :name,
      :expire_date,
      {:categories => []},
      {:tags => []},
      {:images => [:image_path]},
      :price,
      :description,
      :admin_approved
    )
  end
end

productslist/app/controllers/api_controller.rb
class ApiController < ApplicationController
  skip_before_action :verify_authenticity_token

  # add settings and configrations for api
end

productslist/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

productslist/app/controllers/host/admin/products_controller.rb
class Host::Admin::ProductsController < ApplicationController
  before_action :set_product, :except => [:index]

  def index
    @products = Product.all
  end

  def edit
  end

  def update
    respond_to do |format|
      if @product.update_attributes(product_params)
        format.html { redirect_to(:action => :index)}
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # only xhr
  def add_category
    category = ProductsService.new.find_or_create_tag_or_product(Category, name_from_params)

    if !@product.categories.include?(category)
      @product.categories << category

      render_add_success_json(category, 'category')
    else
      render_add_error_json(t('product.category.already_exists'))
    end
  end

  # only xhr
  def add_tag
    tag = ProductsService.new.find_or_create_tag_or_product(Tag, name_from_params)

    if !@product.tags.include?(tag)
      @product.tags << tag

      render_add_success_json(tag, 'tag')
    else
      render_add_error_json(t('product.tag.already_exists'))
    end
  end

  # only xhr
  def remove_category
    category_id = params.require(:context_id)

    @product.categories.where(:id => category_id).first.destroy

    render_remove_success_json(t('product.category.remove_success'))
  end

  # only xhr
  def remove_tag
    tag_id = params.require(:context_id)

    @product.tags.where(:id => tag_id).first.destroy

    render_remove_success_json(t('product.tag.remove_success'))
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  def render_add_error_json(message)
    render(:text => message,
           :status => :unprocessable_entity,
    )
  end

  def render_remove_success_json(message)
    render(:json => {
      :message => message,
    })
  end

  def render_add_success_json(context, type)
    render(:json => {
      :message => t("product.#{type}.add_success"),
      :html => render_to_string(:partial => 'host/admin/products/row',
                                :locals => {:name => context.send(:name), :id => context.send(:id), :type => type})
      })
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:name, :expire_date, :price, :description, :admin_approved)
  end

  def name_from_params
    name = params.require(:name)
  end

end

productslist/app/helpers/application_helper.rb
module ApplicationHelper

  def value_or_not_set(value)
    value.blank? ? t('common.not_set') : value
  end

end

productslist/app/views/host/admin/products/_form.html.erb
<%= form_for(:product, :url => host_admin_product_path(@product), :method => :put) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sku_id %><br>
    <%= @product.sku_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :expire_date %><br>
    <%= f.date_select :expire_date %>
  </div>
  <div class="field category">
    <%= f.label :categories %><br>
    <div class="rows">
      <% @product.categories.each do |category| %>
        <%= render('host/admin/products/row', :name => category.name, :id => category.id, :type => 'category')  %>
      <% end -%>
    </div>
    <div class="add_new category">
      <%= text_field_tag('product[categories][]', '') %>
      <%= button_tag(t('common.add'), :class => 'add') %>
    </div>
  </div>

  <div class="field tag">
    <%= f.label :tags %><br>
    <div class="rows">
      <% @product.tags.each do |tag| %>
        <%= render('host/admin/products/row', :name => tag.name, :id => tag.id, :type => 'tag')  %>
      <% end -%>
    </div>
    <div class="add_new tag">
      <%= text_field_tag('product[tags][]', '') %>
      <%= button_tag(t('common.add'), :class => 'add') %>
    </div>
  </div>

  <div class="field">
    <%= f.label :images %><br>
    <%= image_tag(@product.first_image_url, :alt => t('common.not_set')) %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :admin_approved %>
    <%= f.check_box :admin_approved %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    var urls = {
      add_tag: '<%= add_tag_host_admin_product_path(@product)  %>',
      remove_tag: '<%= remove_tag_host_admin_product_path(@product) %>',
      add_category: '<%= add_category_host_admin_product_path(@product)  %>',
      remove_category: '<%= remove_category_host_admin_product_path(@product)  %>',
    }

    var strings = {
      blank_name: '<%= t('product.errors.blank_name') %>',
      error: '<%= t('common.error') %>'
    }

    $(document).on('click', '.remove', function(event){
      var row = $(this).parents('.row'),
          id = row.data('id'),
          url;
      if (!row.hasClass('new_row')){
        if (row.hasClass('tag')){
          url = urls.remove_tag
        }
        else if (row.hasClass('category')){
          url = urls.remove_category
        }

        submitRemoveRow(url, id, $(this));
      }
      row.remove();
      return false;
    })


    function submitRemoveRow(url, id, button){
      $.ajax({
        url: url,
        data: {context_id: id},
        type: 'delete',
        success: function(response){
          alert(response.message)
        },
        error: function(response){
          alert(strings.error)
        },
      })
    }

    $(document).on('click', '.add', function(event){
      var row = $(this).parents('.add_new'),
          input = row.find('input'),
          name = input.val(),
          url;
      if(name == '' || name == 'undefined'){
        alert(strings.blank_name);
        return false;
      }
      if (row.hasClass('tag')){
        url = urls.add_tag;
      }
      else if (row.hasClass('category')){
        url = urls.add_category;
      }

      submitAddRow(url, name, $(this));
      input.val('');
      return false;
    })

    function submitAddRow(url, name, button){
      $.ajax({
        url: url,
        data: {name: name},
        type: 'post',
        success: function(response){
          button.parents('.field').find('.rows').append(response.html);
          setTimeout(function(){
            alert(response.message)
          },100); // setting a 100ms delay to make sure alert is shown after the row is added
        },
        error: function(xhr){
          alert(xhr.responseText)
        },
      })
    }


  })
</script>

productslist/app/views/host/admin/products/_row.html.erb
<div class ="row <%= type %>" data-id='<%= id  %>' >
  <%= text_field_tag('product[tags][]', name) %>
  <%= button_tag(t('common.remove'), :class => 'remove') %> </br>
</div>

productslist/app/views/host/admin/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to(t('common.back'), host_admin_products_path) %>

productslist/app/views/host/admin/products/index.html.erb
<h1>Listing products</h1>

<table border='1'>
  <thead>
    <tr>
      <th>  <%= t('product.name') %> </th>
      <th>  <%= t('product.sku_id') %> </th>
      <th>  <%= t('product.description') %> </th>
      <th>  <%= t('product.price') %> </th>
      <th>  <%= t('product.images') %> </th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to(value_or_not_set(product.name), edit_host_admin_product_path(product)) %></td>
        <td><%= link_to(product.sku_id, edit_host_admin_product_path(product)) %></td>
        <td><%= value_or_not_set(product.description) %></td>
        <td><%= value_or_not_set(product.price) %></td>
        <td><%= image_tag(product.first_image_url, :alt => t('common.not_set')) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

productslist/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Productslist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>